apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-namespace.yaml
  - 02-pvc.yaml
  - 03-sealed-secret.yaml
  - 04-deployment.yaml
  - 05-ingress.yaml
  - 06-agent-rbac.yaml
  - 07-agent-sealed-secret.yaml
  - 08-agent-deployment.yaml

labels:
  - includeSelectors: false
    pairs:
      cluster: safeqbit-local-hq
      managed-by: flux
