---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: affine-credentials
  namespace: affine
spec:
  encryptedData:
    redis-password: AgBQCYg3yh/fKr5bs8xYYMy394CvqQtuXrpQjvJU0lplb2gJHHbKoV42dykqUmD/V6nd9GMZXAIvZpa114VdBLLLVAW8Hr2v9j9rJ3ObT9tSRJlYxdEMQ77/4IYvYGVFlFLuCXAKZbvNrhBOrREDVLw5TSlbDyR/7ZWXhQkP/Vv9fEuKJrCdoQxcbjIQDFAepsw9I/U5sVefBJttmlJx5x1VakHMgTux/Kq9ErO4K0pQbCHZqBpgZk4wPqm7+L7FXkMPG/B0g6E7PlymAyNxzD4fkTGiSQeGy3V+zw/gYVMMIZ+XH9xa4Hr90Tmox7mYrGjOvgNghUTwPVNmzhKczGtswLDvRKfvVoBMGP3gUN5LT9/X1UXZ5JkrCzrfIs5nqbCDm4FHVttRjRunh3BhTLrE86ggqjrZhXZDGi1LNrxUc0ULz0KqL1aSISYkAlDVqknvuk1b+fuSnCVssnVvI1DhBIRPSaGiQ5QwemdDanskskU7AsnhgtmenFq/7mwlh91oKiqsVh6tXP0NXPWezy3vt72UL8O8qRzPIE2u+bWYmMnlSmvK12cmwEXlnE+gb2McTs1stqM0m6BvSrTDBVDvuDtuoOcVlbYQe1UmqsfofLmwkPpNVByYLfxO2M4IsmEKrW1XEGS4H1YdlnC1UIEFL2+XxmJroM9OiZE/24CARfZiZGvfrqnVD9bWDjJ7mWgD3wqe7qe+6a8+OZl98EyOnQIE8K0m4+d0MQoNShCFK2CwkP8fgQP+C2kVSA==
  template:
    metadata:
      creationTimestamp: null
      name: affine-credentials
      namespace: affine
