---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: passzilla-secret
  namespace: passzilla
spec:
  encryptedData:
    SECRET_KEY_BASE: AgCHSwtd+r0JZf717JwgDolkdFr+7WXx4MiM1HB1LaYh+y2+9U/xmNWWeJA23AIyFz84YRTwR8ugXsGuSHyvrtTFnmnyHKZO+BY+IDccbhywk4dctjKAjTV/mOVlRwBk6H39EN3CTnmcaMLcSjKbkj/ylOnRVhsOw+OVaQHCHBQ0arqNSckGiP1/B7Q/EePUK/QKiAWCtWQFpAKadWsUOIj3Siwlqljgyi+nZLAaRnoePIj75/jU6snouSR27ChC5LyBYMQ6SrCe+NpHJDUVpuvNww1AVqF18U1zrf9YNPlBrZ2EE9+fVQe0g9WuEG40jcMcPUYO6BrZ9AExEKJ35U8SAXF5kMkwVOrDJ6a2ikI7oeUTukSw7C8Kig7FEkPjL/yShC+omrhZwqjIdfNna3lLgh+22piGPicI2y/cwtaIUFN7EE0RAzCIqqwaI5IDotNT7FsxYAdh9EyqhkezgHq/0C1SoJMDMyR5Bl0QC/reHV26UmuKaAKKab3gHX1sF/OeSPbUQcBN3f5G5tu6wisXAl0sTtae2pt1a8qMOFWg5L0ssfNIVtg9aTHcRGx46lR8IAMnIlc89LvsUlz+sWre/GSnYKHvN1XTw7BX2JrHLe6e0p2R88HORq6nG+4G9aQFIFMcEtS01ClJesRAcxGa92Kk6+WgfiAlGFl9M+nTf0f3O9ScWalaTE6jpPoZYo0gWasGT0loukGf+ao9qrcNzL2xwX/wyVTEQ86XlRD9cdECMaooz3pEKvzSUlUxIIuEelxVvpQdHTrRpoCeNVWNaG8jJY07Na4caQhem91ykMjZXx129DmTDWYQcHLT9N6zF9JQRbqigefVUzf3VUd12QIYJkHyj4gO3lU3MrrtAQ==
  template:
    metadata:
      name: passzilla-secret
      namespace: passzilla
    type: Opaque
