apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: passzilla
  namespace: passzilla
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - passzilla.local.safeqbit.com
      secretName: passzilla-tls
  rules:
    - host: passzilla.local.safeqbit.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: passzilla
                port:
                  number: 80
