apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-namespace.yaml
  - 02-configmap.yaml
  - 03-deployment.yaml
  - 04-sealed-secret.yaml
  - 04-service.yaml
  - 05-ingress.yaml

labels:
  - includeSelectors: false
    pairs:
      cluster: safeqbit-local-hq
      managed-by: flux
