apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-namespace.yaml
  - 02-sealed-secrets.yaml
  - 03-cnpg-cluster.yaml
  - 04-redis.yaml
  - 05-pvcs.yaml
  - 06-netbox-web.yaml
  - 07-worker.yaml
  - 08-housekeeping.yaml
  - 09-ingress.yaml

commonLabels:
  cluster: safeqbit-local-hq
  managed-by: flux
