apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cloud-credentials.yaml
  - volume-snapshot-class.yaml      # NEW
  - schedule-daily.yaml             # we'll add these next
  - schedule-vaultwarden.yaml       # we'll add these next
