---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-secrets
  namespace: vaultwarden
spec:
  encryptedData:
    ADMIN_TOKEN: AgAtnspe2U1I0W9JYcp++/kC+ZWX2m07LKM+zmFOvATiiFsuN6h9tPQgEEcL5U1VfwGHPXufM39K8RbmZTfRuoShNRnUb8/yFmkFv6P3bV/8TitklNqjnmSd/KZWswwX5ueUz/dXXJEKYvMuBbnjEknwjFj1JGEwGHLrGWgoM7XhcDeDFus2DF0pqhuniNdorpnWZQtNjmAUCMniKlUMAsrNSiycl21D7QuoU/9WAp+D7CAZiavroZHqRhyZmV/Fad8zBGgm0Z3LJ2NBfupz4weyGh3zsQPdEafvSBAJ//vccPgnuI0dw++A7M3fRWkwaOx7h3AdKxj75yeJuGFlmR0QSfqUt9M35tQlI/GHNAPxl/hUXu/BS/HL67AR6WL1NOlQHZhPGjrPSc7nGnJfjmXSDrxwtrg0Pk/Wi70xFcG86VS3ZfLepEcpZi8tzbCXv3lA7Oww5WZf0LFfhk4b//q8XXMJMgB64L9rAQ7FGBmBM0GxIhvi6Q9tFR3b2nyP8jGaX1OGWGhWIg5XO1IEdIH4+uiO/n/6AGdKQ4Rv2IhDMIK8a6judM5q5ybOVaLGqAdsUBy8wIuOeF1Ezmy9aLiqMbeCNUTY9LNTUOiAiV+ScHpIMlNaH6VuGh+iDZ7dQjnKrQ1ETCvy+Yev/4ISUKSly0bGgnm4ePdUgCUfr5198e1rX9yNu5Z2v6QIjC9aNZEHx2D32zNtut6UJkFruptkOPi8uShKvAUW/sLS1wA8PwTO5botLGrlS9Gu1qCwMAriqJ0/RyRzjKtBeE+/UAuyHJVB0tzgPQrYrSYeRCqdZwsANkDznZAfuA+ty/L8bFqcixzMSBWzB9LrznOj16edMj1LuUwj
  template:
    metadata:
      name: vaultwarden-secrets
      namespace: vaultwarden
    type: Opaque
