---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pangolin-server-secret
  namespace: pangolin
spec:
  encryptedData:
    SERVER_SECRET: AgBGHdEVBbs6ZHYWXrrgkza0kwKpbck6ngFbnrAtt/IVmqLk+856DOvc67z5kfCvWmkyuwCDf0PAUpyL/5GJxf/P1+U0S9kQ0frCPHBKxiyV5s6GKqU2/+GHkySgwqaubUK61+0GMZjFgl/MYSNVrQx56K/P7dW0nVROdAj6pkx2FjdVWmbIQJEpWVADdSw0n7/RCUUcZgO5sZYBlpn/1FaS6hst7mJon1JI2dvCL3z4UxLD/B6HqAVvjF7a3aWUw1lri4bqDrlJSi+JRbSNB+vojTwGsqND+DLCFPFMBEj/P9sD/AR13yfc+gW1QHMLCTXWSvU+mC7zvJ2/R9E5Qz4e6jmu3EgGNv64bHOB9q7Xakii4i6eOZw9Xng4UJREB4io/DvlNhrQ+iURkPzfLC0ofjocgZg2m+AbcJ1/qstS5mgeigZNXrcO+7t1p9E1APDLFmS82u76cvpv54nn7OU8tfvPPKUX3HzKX361oWMjNORSfe5XJppme7Jci0EPQjUTT+jlQZ7yxaaB50Yd/h0e/sTXLnAEMIV3yBNUsy7AzhSY7Fa9bW0owPz9pcuWbaU0LWk548730IfCuCT531isVqTZAW8DZchrLfbaBM4qmitCiAz24xhSsO/J9rDsX6mwoQRalxp9CYWs0WoofESQot/Ak57mWSYCWZ8hIr6v8yn20h1R+F7RiMFz2UDoq6mfQE3GMdCOvT0FwzPEoahUc2NexLwZsiBzdEA5R+a1R/4o9apMrmKsOSqvvenvt4iz6YrL1ATMeZCMfwULonph
  template:
    metadata:
      name: pangolin-server-secret
      namespace: pangolin
