---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pangolin-newt
  namespace: pangolin
spec:
  encryptedData:
    NEWT_ID: AgAIOXld2CEC6epW03JriVdVVhiX5zEdNMdzgsXY/jApWMShmHcF8mQenmeiUl/KBjDSyF480Iqv8a86DKBGJO5QDhVVyWGF+MbC1SQh1ITmg1FQPTW8JtjMRNX0bGTA0lPMnJZKA1dmLNj6+Q8w8HbEp391eKAYzAQMitiGgv5HkE3U8d7uuTV5uw3sOQIVBKFt1JKdUjlepP0gLlV7cUnL2eXZRRk0NHwtpVANLG6EDyTHgJ0Vx9Q29zv5fj0F26V6NgWE3UWBx8O1N3yj+DwaWR6cpBijx+rlMKK46wRvhTA8DkPXGw+d0A4NaXyVJodrS5cItwQEt9FhO8btxI6gjefNCSOgh3159SQyfg5qGZtg6nluRZNSWfzqu99klwW4+cPINvZutonfIcoxY3rjcuQMy5RHByuddHPLlOo04pO7pJQlHjNQhrnVWfoj1N/uWPmsEeE7ufGJYv+qR+w9D7ZnteWWTnYeaGJFMNX2tH0HoVpzVlixVGpkR39cVc0eY3WNm/FmFwmmfTgD/MYYxs0wnqKVohBeMZMzbgo28Ua99HkFWsSd4PYwFTLny6iJLvJ5p0ZDul3SQEgtd2fVhrj/5/an9p8OoGzdgOgvZdYj6jcBdh4wDiUaUWFVKD6XKL0uDjij7uhJPDnoaQkg8jdazF1CNoJAOInVF0Ccx6T5KycIzReiCCiDWP3opW6KyqDIeZMsMUxttKH7I0A=
    NEWT_SECRET: AgCBeTJYUanSv7ShIW3ki4PEGxDq0LspLW3QKn15puiWo2MAq7RVQ7FHWTqdHvnmq2kzr2So1NrKzsxRaSxAJpI6d+pm2T3k82xdkUIYyoadosu2q1J0TatpA7f35swsB/wGSnGf7OjCY8Bb6FAzJaros7xK0wxA7413frHGDy6NJvPCU4aIPAUh3m2E/wfP108g4xLpl0S1jCSsgGWl5MGaYl/M3SHIRa4sEeKJI1OtZQgWRv62K6ReKa/ou9gFo9vj+2kPgNC6ciY+PijBCL5HjyvWCggiMlFNZswesrhMRYqrfdApUmVipqbtyCyd/DuBaj5zG9yC9Gjp9bO/NflVajVnlIDprS8YHkLyyytIHWIpCdUqM9x/ckIt5YD77aVfBZRpFYjUaWLZAfvQagor7vOn5YhWgFk4yFEzsJlSPbXLkh+dy+rZL1k7fl/O+6l3ci/I7/8at5/DVbWT5rAJrJqsdflYY6yLrqVL73VnxgORO3X49cuNZXQc08r2fPceQdg5xgqrDXhzB8zAToQrjPfhcPZ1lBkem+Eg8+4jgVHL12fRsHb6UA+i5KLOMFKhrQShYbfrKgvog9mMweV6z9B8uFv6DFgx7MIc1XCwevknOCGugk+8kh3YKsvssSky9HaHUkyV/y3/AB8nDoj7AcvTF+a84ykWGs9mQVBi0gDjAUORg1OfynaP+Vteylv/tABj4jDBfl7g0RWeS/5MQZ0+OQ5yqjc2iOEUbqPusm0+bbNued1Ae/eOsZbvpto=
  template:
    metadata:
      name: pangolin-newt
      namespace: pangolin
