---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pangolin-newt
  namespace: pangolin
spec:
  encryptedData:
    NEWT_ID: AgBct7GjG2JTprIDKokUqvW+GjGFXcn03eEBOKQf9ND+EJyHcG0NVIOViEKLpjji9RrGEu1hOKNtGPAG7hsxATwPj+X9gqZ28NM8jcnZ2UjmZtQOL821Nr02XMpiefbZUfz/qn0POB2/vEP3YAfzwIZMh9ca4DFDSpUusnJ6xO7mK2KVZLCJDaXFpRZq+ZUI8lkN5pWwm0UUWayrZvS8IIK4VjM4DnFZEzMZheOOh3aV2HF1c/TqJ4s6UiGufT8BbSFV+sTLC97Feh+GdviBZj+vou7YCQyXXi4JyOQsEFznfPIS7KFcAHq1k+hoh/bYbEtMNU7WobrKgi18cUWjEwZtxcqGJPW+eWWdHAaDQtUSoFIw+PQ6Y0omtsSXiJalU7BdF5x0A0qG5Mo6VgIhXQzK91j8FqLOFP8OfmT5Gw10WasfkijvRXNJv/PM191NEEMi0dzIWs0eEUOc7QPuBG8GjGm0A6SqZYC3ImykChqi1bvBkYrskabJSST/N+hafZNkUq8W66EVWUcYET0DYttgZUKFUvFJCq3N5jkMDB03320uTjGtBmH6Mch6KF7x0KUqJzH8zzBIMU1dnUBmhzMdvaB+sRWnJLgbahY6vsZOpUgMqROYy2aDSMmvRGOZ420Sd+4HEidEWRxU1YxtUMfmjZgZMl7VH4TA8BwkgBTFI5lmixmQQ+TdHdIGy5CH043ofA6hL2IQfl6ovTXreMg=
    NEWT_SECRET: AgCOD6THaJVzRaKH2vopsT62CKgZq893gSlyoN7rzOpByp7J/OZEQw86OgoIB2vfGICLXkHNhRFvYU6tGTLKQyxbKLNMjL4hqhF++/dZ+EURsF7+iseFVpgVFKCHA6ib5WcVCbMk7sef4fPqYi2pt73cdqOcewiwfWO2BkpGBWhF3YlO6lW5aS2hjllA27R4vvEvo/NHHPs00P6HMZFXUBJpsmwxHe8uWxKml42DpCOqDbP9++2CeeyImKw60/BJXmfFElWwzHlnd5anebvay3zqkOxLs/iZD1Klh1KaNZ9Alrj+OcVKxpwMOkKDRZjNuKg8/xb+YD9E0UPnvvITtsk2uNcgKD7oTIStNhZYWvFCixIXodNbsZSHajuzLfvkbNSe8HIIcENpAui4rsv0CTta+2p43OZs9NputG3eLGpYrlzsQuvqqWdmQoTv3i+jtpHyWzOpsSC3RhP8j2wMkBMEoG2NOK04J8PTmaXqJW9L38w55tYHQvdgiVpvPjRQSKbmx8nGM/o037we0KgAP9XFhR18iJED/d0QwT2tf2769lM1lK7uNvmoTdFECzsV66vGFiM8Pn1PNyvbm833uZpZDIiqiahC+x8DXNaP9WT/T7S2gW9hgZd/oArVoVzNo5k0wkxx2DDckr8lPMiuPIyYH+ITlVSZsGz2TKT3x83YkWuNeiIuBP0KW/+gl76mWDST+tqbJ21+WV2tCharMduDi9L2/Z/nNSMBD2jZhK3CXPA/EtJIbHPgDlshyUpfjoQ=
  template:
    metadata:
      name: pangolin-newt
      namespace: pangolin
