apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-namespace.yaml
  - 02-cnpg-cluster.yaml
  - 03-cnpg-scheduled-backup.yaml
  - 04-sealed-secret-server.yaml
  - 05-sealed-secret-cloudflare.yaml
  - 07-traefik-acme-pvc.yaml
  - 06-helmrelease.yaml

commonLabels:
  cluster: safeqbit-local-hq
  managed-by: flux
