---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-credentials
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_SECRET_KEY: AgAnDe5U/Ich3m9qQ+jk7CB2DHLiRIgzsBpAaf8aOsKEsd5Z4tU79AqvTx1p2XCfVve6W9bD/UxoGtVF9DmE0t01Y0HEVUcn5HFfnjbVTByu1DfG3DWTxW26ZUeaMSAwgYcXcSyoxaUR0rQEGJg0SUhSIqqoC2aFKsjeznxag91/Lv0vqQdSc+e5tnofBGgeJYIr4/atjV42Ta2KVe5yOfVNKFabl3S8pSbtmH6zkclPJCUjDFPSdp6kaePdd456F+5aUMWUviy1tUwQ9SvSlIeFnzycPFvaQYLR0GHtcjMh4eibq1JzT1EI7+btP2PeUJ8teRo46sg4ZdrJu30EA5L5+stRywL7ixX2v0yRzjVH03TrWo3OtIqdYkBflAkEl6QgNjsccDMwm9ZlO+u7J2dYfUFPceubbiOLU8w9Jt9C2/+cNF6GN1JZFJaHFNYzBpSLpEF8r/ZCBdGi/a5dSASBFK/eFvU58Qm5x77DcXx/1EDVW8EBFMcdTt/lf4cMD5hMNDsZcISNnBA3qs3YREzVxO0K5A4GXzoe1AmCXosNpp8ZT5SidUAUnMlceRm31Czem/HXjCNYLJ8g+AJt4MCdr6FU5y/Ol9J1FXIFvx6wfTnFyFZPGS1GaAo+gofEXG0wDKCMYZpfgYSS2+FZOU7aUB0sRR1iVpJNwp6zX2rkyZqcMbj4zrgXWfI7JUJ8D+iixGGU+vqOrepJfSRez2Sm7Z1ZY+ADmOTuG/eaWQGYHMZ9+oICdryx
  template:
    metadata:
      creationTimestamp: null
      name: authentik-credentials
      namespace: authentik
