---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-credentials
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_SECRET_KEY: AgBnio0fvxkB8OplWOT3ojVoimB3uNCyFZkApiS+5u5tulumaq1q55vf0dXKvYeB5Rfwk23kBG+kU7TSOXHO/JjPcTm8iV7S6JzbY8MqEy8oqdlI325nmeC6nMklfqcx/4HmDNnfCvyMzEIeZej40nD7DY0EcjzKmEpZkLyTAhJNS7fG/okjnCVuUsvER28TUHD6+z53/TmpbD3ycf4jhl6pKsYNXUSALe+QV8Y2dWOOcA1WmyTp3HZSs97b27KWn1vTOimbcOxveDu8aJo3gYiaZ6V2PFV2EmDDRpQDoa2YAVVVOCWKHfGFfJ9QOkGxh+vijhRcuQoPJ4z7GLUmlGWXE53EtEqS+t3MGbMTR6wGlTvDDJ4SbIpzwvxx9sXdjTcfCrFG/igUe2qwMOc1SAzjbEiADtaWF/WkE8/r/1aMKw9XY9+qnke3OSCT0aKNU2oRCRjoVGqmQ/vSvQuovLiwRVr0Mc7kMD8r8kVHGjs7vi991iOko8UjEWZ/B9rHhC5QXAS0kW3g/B1s1G63OGwojQDje0gUEBwI/CoS5Y5BS9ZbNq7JwE2XkvFRAsPAkmPjzXPBZAE1nwbaN5HPw3u3wgmgGb33xvl4cScL630crZg1BLkco0ZXEyOW1a3f/JxaVSa7aU9xM/0ro8xAz/rj2gWBcS6wLHnEPi/e86JWDkiJSiLOH6tCBUF1aR1Azo3xNC9orcLooLlK0ZjRqyxeDG99rUhIVsAY7rD5sJgivBk9xKB9gE7gSMlSER2PW0Q3jAgKlq5O1sg2u6eRf2fh
  template:
    metadata:
      name: authentik-credentials
      namespace: authentik
    type: Opaque
