---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-media
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/component: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-truenas
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-templates
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/component: templates
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-truenas
  resources:
    requests:
      storage: 1Gi
