# cert-manager.yaml

---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 1h
  chart:
    spec:
      chart: cert-manager
      version: v1.16.1                    # check `helm list -n cert-manager`
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      interval: 1h
  releaseName: cert-manager
  install:
    remediation:
      retries: 3
    # cert-manager ships its CRDs. CreateReplace ensures upgrades migrate them.
    crds: CreateReplace
  upgrade:
    remediation:
      retries: 3
    crds: CreateReplace
  values:
    # Match what's in ~/k3s-lab/cert-manager/values.yaml
    crds:
      enabled: true
    replicaCount: 2
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 128Mi
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: cert-manager
                  app.kubernetes.io/component: controller
              topologyKey: kubernetes.io/hostname
    webhook:
      replicaCount: 2
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          memory: 128Mi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: cert-manager-webhook
                    app.kubernetes.io/component: webhook
                topologyKey: kubernetes.io/hostname
    cainjector:
      replicaCount: 2
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          memory: 128Mi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: cert-manager-cainjector
                    app.kubernetes.io/component: cainjector
                topologyKey: kubernetes.io/hostname
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
