---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: photoprism-credentials
  namespace: photoprism
spec:
  encryptedData:
    admin-password: AgCVxmc4BslHnHp+pWGSnC2Lu0MeR/np821V6HYncKPOI6oZ5H+eN07IFJw9Yz1WdWN2djdwIwTPk09UB5EUtj995bbn01+xK224AMeuq6Lp637L+5QW7EAtKsf45x2Cm2Qnfh2TQYaKVNCWnGYGzlgSK6R8JyrODFXgxmLoSxGmnVa7Ov7KZA6biO5KfZHNAFr16R4SNAD9R8q1MPYs2tfQGUU6gePLXzDSEWxuffJUiG00PhXf7HGs3wyz7tLg2CnPhP7tzzrcSnojQeCnq6oPvwvIZZ2NiZcJrGUi03g4Iu93DqLokFkiuIWltWWUD3N1cjJHKmZzAgeDCzM07k4cjRyzfScq11HClT01xQo6wjEypQil0zqGAQ8vtLt0djifEMQxnO+kmqMQiLgegvDyCE4cs2T/1Kwl3sP9ZaEGpbMKdPMyYi4Tt2l3uaDhDM6H1SMkbw4ttBZamG+hH0kJc13pblLy96X5HX8yFsWyN1ybKFJND6PbwS+C6mulujEFVOeYRN3YO2hqLR34M7MTwrv2cRhuWy47prq+MoJLC1A6VStmEFRngQyie7PYWEfMZTG9yU6IkP/WbYTWHkl9HawtM3+VR2si+4zLwroK3INVVjv0rkEhJ8nXSmXUhobCAU9w3SwKDck/I2uTYc91r4Ejs59zo3oUdTzuJbQMOzeggCtoo2ObTeUxYQ8rIgfYYdhsRB3jOSrOTwOhkhFGpl4L
  template:
    metadata:
      creationTimestamp: null
      name: photoprism-credentials
      namespace: photoprism
