---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBXV1HlE0AbySP+SVwcP8IQq5miobEqPeK+TqNS4nNGVjqPLtqizrDIQWvSkDPYNHYDLPHQ6omgIiBkCwAI55Dg9ojKQK1coMkH8Lvy1l9UKXuc018p6ojYBvlE4NS1XBdHVQ2rc9Q86vL4iDFG23pjq0Y2Ik2vv4YNbtL+j5bfOo+8wyl4rHy0wZ7zljfF+Q3VT5YiRVkilczFLIy7YvmGR8kqLcX0pP08bQsfx9ikR9p88GouXeWCCu+nGHGKWViqJhbANI6K6bTtYRFR6AfLy33nTH+wVtgnU4VvNHtyfiFVf9o6Bfmy5zUr/i3jpofH9sQdPoTwm5P6Z3eouI16eMI8UXcznnWQ9IcXd8URm6B+cpxiU5hqkrCbmvS6y19NpvLsUm3yMOvSH61U3uqisIeL0/KbAOKX/oJnPJ/bqpTblYTvGEhgFPdnU7u4AQAjl9BJY6x85Mi+vn8yEQddDGKMZN6SCQFAtz5Y2/C5yKJ/QpJvHIWIrqy3fvxjjy377n6Hz73zFi0WLjulqp3/X1qA2xG9fK7LJClAL/iW+dQfgZ+VAXTcV6ql08MBBPyzA2fdxDbnXHB/1HAtirLio614nACphA5a8Bz9XLxMsmPCgNzET+6tFaNQPey4nL13W62zmaV45Q365+he9uPO/AeK6s+a94H9ReGRpfKSOaRISyvK63HmxDPoESv/Dssk3jNIhq60YS5+h0tlNA==
    admin-user: AgCo4Kpiv5way4QBAs6Aopq2yOXoVOSi7D1fKyF8E0uhFxzQ6s7nIfwWALksXMDX+45oIj/UK6/68qGJxGvGgVFy3DBu28SC8xdLKz9E6CVxvyv8hx0IkGB9lRG7ufiHteCsUO6bYYj7yiGNAllr5sX8iawe6+ZYxkmTQ9EtATWfRwlrxMwBZiyZJ3GgBLv/+OmWcxGr3Ev/pczQyV2EPnuwKKMAYBsudwTn8SnDm/XpzdL44r/uKrTXGNJUMG9WwpoVDuHOQpGWbxVAn4ldPaZYmzNwou0YLOdjCS+CYW2rONv/r7Q/GKIYMqwmonL343qFa3A1/P3Absv6+g+eqy3GNkNCCP3Sy9m3IfeMtpu6G1rWQ4IqA/Fan5K0N1hHHDgQW5PXVYGqcAiuQEhyD30eYre3C12tYMaeE8ZgdXMTBBQD5AELvaPylzOGZFIT25n46Tx7yeL1XtQfrLCF0rO7U9UoYECCUaLl2FaGlThhX9wl4nKAWc46SZa3ogY5w5IQA0bSvdK0gEzZfEiA8DLPcM3ejr4551d18poQqzSXu33k5kHsaF9FvubbjHLPLTVghjrGdUmvqdqmPlG72qr0U+YUHK53zg5jmBGLI6cLVmXn66oRTQ4hlJgJ7M+OjXw0aM761KyzALeIlxGIHWKN9CkOAPQCmd9yxyJ5Pwbu8V2DjjNMa/EzI/PBlpImSrpURFcvMw==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
