---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCqgn89/7z1nmZlGDAAq8KZoJhbE8ljxL3SA7DDb2xSwmoUE1pxS3dGm5q0iWKABbt+rpcF63+DnyDMItFKc753zrq0Cu6hazkOzjpnzDe6GS8vjw4oy0fJoYREjC9RfIamV2XLPq5zpc1Nxsj+PA3/lNz+p3adSxuYplCMAOGPPXoiWSNulcjlsW0za8FdJXjO833HoPCCadUUNaDKqU0AvOmzxWp+JOavCHLPORxPyZ2rpVuD5JNWOU9v6CNi0RStkeNlKBmIR7jaeMPyCiXxf5Ze3Rco5yKNgl7knRJU/fggOGhOsaYd7Df4nrtEMiSlrKNFY0d2xNpoS2CKrdO9PrIrkCqxY4vZLSd08ZfSwDTKUZ/Wx04DrxH0jqxj71mI32s9D22qt5gqr2mxVS0AWdZ0yVtx2EMHTKjYuPGpxymsJZianSMoMySebGNON2vQOSgq8x2BN74Mwexinn7b0mzQEeIh5Dhq975qE3n7jKKoUdqefEAPTVUV/+vm2uL322Zn7J4JqBG4PvqgUdE2ap/j89YcV0rSxEvi6RaNamsbwYOnubL8nDFlyVcxGkqXgz9EEej89tnh79XbmnScU79vQwFNSXXArQIObW39H+3A63SsFYQ3qL+ERLLjP8cYIRaTkya2TodyY9zyTmISJjMNdpQ0zGEFMqA5B8V28PH3LSOn9jN1VW0eGIVM6t5G+Mu1vircsxriE9Dm+w==
    admin-user: AgCOEFbL4I7cAn53sY4cR6JMRtK5v/yVu7HXwF/g5D6VfTzPwPKa/bJLJWQOnzKGQUt+KvMCAbtXiEy9rSHlChr+BJlTKq6oCh/B7j8JPzFkMNa2ijppyccAerPH5rgjOftdwbeOb2X/rUobzBqs5PvxPk4jza09lISzv/3vCxyhp+1Hb4s5mKscQDQyOjK5whsdPCFF47nL3a84bIMrrS3J32JKxkVxz/nT0m4EMqVzmvSpbdDPl/ZWmXeUagFVdjuUXg5XmnxqJ5A5NVqQegTz9MfV27HPq53Gt0MHvMgGIwGNJf8Ubs5lj4TD8HPyQlz+drHYe0B4du920W2DmkCWKQaOA9B1mBZajXA5xHCiSAqWT4C8NwVh6ojjHSCuNAdGKmstjyTVoPkx6Bl11hQf+DBetWFlRTci6IzQD/vvmSEy3pQgCoTlPd16DuywhtzcZElmdVbeCt1sY8dDJx6dMwnaA6mf8Tz0504aaYcpVuZyp0lO7kEgeAgSg1azM+8t60vlmroG/D0bBoyQkO/k/3mW/i9UZeH2Emd1FnBewKF134Tj+0hFmOWq2MRTKHpyKA2BiZl8d39eQDyVXKgn6SNYFwkIP22Ean9SainSd7DD0fqSS62Nqxx6WcqFpj3LKYyrCpT0rrUXuFlIxrcnRbqWX7FCWMAB1zBRJs1rv3NcB1VbFDrVlDYAJ31crHJOV9ybfQ==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
