---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloud-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgAKbVmjvHlVeoOVjTk6Yp6mAm2e7V8oe4PP8Nby2OTkavg3kJahi+wcqIZ8QuXKOt8+Lr/ahQ+XCXmu3SiW/vRGip4j4XJ6yqaPyeRPYNNPbSQf51qqS/wTfii13ygXe1PDPGZsi1qgGY4/8DRaUH229AV6mwJLgV2PHDxVyIy74IbhfIda+5L4jmiixK1cyNnxyW3rysfMkpvPRuEZLRApu8DDp/9avsqbz2ys0PN+OLmc9zihS3u7ol12TZtsPLSLLCTkPL3SwSPdjZy3kg3V0cCbBwCcCMFc16bjMahh/5WO5SRvdsCk0OXMPz54uc0uZ2qvFkPdy0ym43Jt0prSm4mbn0DSSduv8X+PKxi1fAXGpWFSIPocUNvZshvB7jNSSG5wAPPRj3kLkFkvt2gFuARUoYgdhrtFYMbTZAdVov+YC1kZCwWP03wk1pCxgwkXiCasYJ591EaFa3caOBY+o6nc/dVj16FUsY8wreu7vClP6cGoDOMbFy3RE3U4C+2PuXefmwcNZbUbEGvLAJBX0SX5CLUFGjXfIaiMCEzfcuOE4kqmWzeCfXAKOuqEs9PffujECx1GVhelDeKKsIdEAlMT39GHgNxnoLgO19gKaSj1OnLpLzOreZkM8KRGLxsuTwwfW1EAEh76cp5xYDWRB2bY9lbJpqEPgiXCO1CEB3SOEV9ERjjmSeWTl3t9PAYhqKUYdG2L5edGXhrExSxdkozeoyTSVISKkLv2GLJePdpp4wijt3l0SDbVslK4pkvvgGpdza7pL/jt6aisse+G8DKQJzk2xNkRXmCKoiGweGpID+A26jHXYjYBneatUTFriHJngfbncUUaaVY=
  template:
    metadata:
      name: velero-credentials
      namespace: velero
    type: Opaque
