apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: authentik-frequent
  namespace: velero
spec:
  schedule: “0 3 1,15 * *”   # “At 03:00 on the 1st and 15th of every month (biweekly).”

  template:
    ttl: "4320h0m0s"   # 6 months retention
    includedNamespaces:
      - authentik
    excludedResources:
      - events
      - events.events.k8s.io
      - pods
      - replicasets
    snapshotVolumes: true
    snapshotMoveData: true
    defaultVolumesToFsBackup: false
    storageLocation: default

  paused: false
