apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: vaultwarden-frequent
  namespace: velero
spec:
  schedule: "0 3 * */1 5"   # “At 03:00 on Friday in every month.”

  template:
    ttl: "4320h0m0s"   # 6 months retention
    includedNamespaces:
      - vaultwarden
    excludedResources:
      - events
      - events.events.k8s.io
      - pods
      - replicasets
    snapshotVolumes: true
    snapshotMoveData: true
    defaultVolumesToFsBackup: false
    storageLocation: default

  paused: false
