---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-b2-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgB+wEG5ArPDu/VqEg4QFO/yKE9ifDmMf2Q0Dfy5YbZrqAlMTmvOr1xO5pUtgKFmp6KLSMZ/e/OCTadwD4c2JsBqB+yxxJ7Ws7enfB5tCuGHQfnLz+1nccIPGbqKMHwXzSRNli2manCjnlC6EAITWo1bB7+S2+wKdu92reXPlhaP/3Yp/FfZimkFt24O1bFc/h+nzkxErnSdR/DoCcDHNzxF5kWFRa42eZbbgX7azGU8V8k5I5OQDutq61hAr79UJqFjh0NLM5hkh0SgVSMpm1ufzsMoiJk5U9NzUdX9voV3wSkn5yQ70nxSNsG3zMzr8phsrNvTTPA/Uc+fPEoLkXrQNDjNsnXxPttgqm2B74dzivV88fwfqKz+/uQ6ngPovj68HbtLm/H6EFUwuyp/twj/2BPz8JMLq2FXGLcNmOAQfH3QrLsoUAva7l40yOOOoADFXEpz1B9vZ7i5Xyeg4GwqabXmlsPCyYe3FiUivPSAd8vXgUioOP+BuSHHe6qge7GtRedonBbsVeB3ijOH8vWFgE/Ju7XloT2MIBrEmPKZ4Q0wJD1Rc42nDpjikkeCVLms5hO8nmJC5hG1E31l895ZgMNXulMcUvSd6dTF0P5R6yjmlDDnzsR2roWnZXDE+dTR32E92T8MRcL34JVNWofuD7abaM/REhrZkPLtzGs+HbvxX6QN1hX17jvlxuYa7npDPaswI0XapnQvZvAPXDD3XubFi2aO3muj5YRXwqUn0BvPVxqkG4q5ajGemotRSaZLRebjL9elXS9QBZZX7YI66PQM9xFJuE0LCFJShkru3uipl5ZBwty34lynN3z+tEyAefjleNqdymlYOm0=
  template:
    metadata:
      name: velero-b2-credentials
      namespace: velero
    type: Opaque
