apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-namespace.yaml
  - 02-sealed-secrets.yaml
  - 03-postgres.yaml
  - 04-redis.yaml
  - 05-pvcs.yaml
  - 06-immich-server.yaml
  - 07-immich-ml.yaml
  - 08-ingress.yaml

patchesStrategicMerge:
  - 09-resources.yaml
