apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-namespace.yaml
  - 02-cnpg-cluster.yaml
  - 03-cnpg-scheduled-backup.yaml
  - 04-db-init-job.yaml
  - 05-pvcs.yaml
  - 06-guacd-deployment.yaml
  - 07-guacamole-deployment.yaml
  - 08-ingress.yaml

commonLabels:
  cluster: safeqbit-local-hq
  managed-by: flux
