---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik01-credentials
  namespace: authentik01
spec:
  encryptedData:
    AUTHENTIK_SECRET_KEY: AgBW3bOU6twz+uDN/9jtgDUsqoOzlEYEmKxNl9T3Pv3KLcQhFPUsLUw0oAztJmMirt1GDV0yBtLqBHNVCr0jciJTeORUfvkDqx7ugPWkj1yPmjcZZbPeo7DNxuI2DjUYOcgwTlNbGKMEd1XNRsY+DYrknndBsjM3P0peqXppMizM72aoLZL+GEb+XxkkKCw1T54asRtuq7EY2xbylxHRShD3bg3BET/7JSubBcVLGEekuogC8IK3zoG3IZQz9KkjBixGH0uBtC+HCB1CqiAyVJJY6LerWwwQhuv5kwzwBmsr9sBDsmIbInoPohSbE87THGns0WFKIafZqYCVmYhaCl3EJeRGQnzj7QNZcnpUrrNKw+Qfz1+1B2bWaJKeYiDjVw2ix/doW7vTk3xG7J/H3Vj8NzsicO2QMFG53ejLQZteoi23dQJulK+uI6qlDkWVnyQB6vtjxypOgWhjL5IwkxozZQddUZtWpxM9ZKXzRDcmSFCzNIHQ6/DfLeqoM+kIsVHsbKtVcUBIiJLYZn5/O54GCbSI0VOD/+zgMEhXAiWLzL3e06tCGvaa1sFSO9l6KLP0CTodpoRCOrKmctOYOtCkn6gFCSAtG6jrgtqNDVY9ovNPegBJ/KHaV4dU3oGNEBBajdMkNmh7yxlMLUrG/KEbYnn5btoYvrIABgXdYyvG7UXEZFgJAe9xToCLs4bd2hAu4y4hqyPtbv7PSdo/0HSQI173xHBeA9iSHLkgoEFU+wbx+8yipNd1
  template:
    metadata:
      creationTimestamp: null
      name: authentik01-credentials
      namespace: authentik01
    type: Opaque
